<a href="https://colab.research.google.com/github/Jeansds/Curso_Udemy---Deep-Learning-com-Python-de-A-a-Z/blob/master/Projeto_Recomendacao_Filmes_Restricted_Boltzmann_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Maquina RBM Codigo:
[link text](https://github.com/echen/restricted-boltzmann-machines)

In [0]:
from rbm import RBM
import numpy as np

In [0]:
filmes = ["A Disney", "A Disney Retorna", "Ta na Disney ###", "Perdidos em Marte", "Interstellar", "Apollo 13"]

In [0]:
rbm = RBM(num_visible = 6, num_hidden = 2)
base = np.array([[1, 1, 1, 0, 0, 0],
                 [1, 0, 1, 0, 0, 0],
                 [1, 1, 1, 0, 0, 0],
                 [0, 0, 1, 1, 1, 1],
                 [0, 0, 1, 1, 0, 1],
                 [0, 0, 1, 1, 0, 1]])

In [5]:
rbm.train(base, max_epochs = 5000)#autor indica 5000 para maximo de epochs, mais do que isso é overfeeding

Streaming output truncated to the last 5000 lines.
Epoch 1: error is 8.93578932800828
Epoch 2: error is 8.737868384094073
Epoch 3: error is 8.637915184924557
Epoch 4: error is 8.404604399991635
Epoch 5: error is 8.259675936832732
Epoch 6: error is 8.172098173159009
Epoch 7: error is 8.126404867270665
Epoch 8: error is 7.985048308280875
Epoch 9: error is 7.806042093029503
Epoch 10: error is 7.782390288196545
Epoch 11: error is 7.794737405593776
Epoch 12: error is 7.821454957075364
Epoch 13: error is 7.570314828503826
Epoch 14: error is 7.723059248897874
Epoch 15: error is 7.314861110189913
Epoch 16: error is 7.4061471818713995
Epoch 17: error is 7.258774894025982
Epoch 18: error is 7.495609551125756
Epoch 19: error is 7.236010277793697
Epoch 20: error is 7.158645743102004
Epoch 21: error is 7.139531574556504
Epoch 22: error is 7.107186481989933
Epoch 23: error is 7.279315295037018
Epoch 24: error is 7.285629001470977
Epoch 25: error is 7.07363588167625
Epoch 26: error is 7.0464197808373

In [6]:
rbm.weights #segunda e terceira coluna = unidade bias, cada linha a partir da segunda representa 1 filme

array([[ 2.48097962,  2.32882881,  0.39582866],
       [-1.03426658, -3.29449446,  7.93095333],
       [ 0.26186148, -7.2718123 ,  3.36595908],
       [ 4.9523605 ,  3.90351221,  1.89263149],
       [ 0.94759921,  3.6208677 , -8.22879884],
       [-1.31521182,  0.61012242, -4.54995585],
       [ 0.95285735,  3.61683495, -8.2313893 ]])

In [0]:
usuario_1 = np.array([[1, 1, 0, 1, 0, 0]])
usuario_2 = np.array([[0, 0, 0, 1, 1, 0]])

In [12]:
resultado_1 = rbm.run_visible(usuario_1)#ativou o segundo neuronio, o primeiro neuronio não foi ativado
resultado_1

array([[0., 1.]])

In [13]:
resultado_2 = rbm.run_visible(usuario_2)#ativou o primeiro neuronio, o segundo neuronio não foi ativado
resultado_2

array([[1., 0.]])

In [14]:
recomendacao_1 = rbm.run_hidden(resultado_1)
recomendacao_1

array([[1., 1., 1., 0., 0., 0.]])

In [15]:
recomendacao_2 = rbm.run_hidden(resultado_2)
recomendacao_2

array([[0., 0., 1., 1., 0., 1.]])

In [21]:
for cont, value in enumerate(usuario_1[0]):
  if value == 0 and recomendacao_1[0, cont] == 1:
    print(filmes[cont])

Ta na Disney ###


In [22]:
for cont, value in enumerate(usuario_2[0]):
  if value == 0 and recomendacao_2[0, cont] == 1:
    print(filmes[cont])

Ta na Disney ###
Apollo 13
