<a href="https://colab.research.google.com/github/Jeansds/Curso_Udemy---Deep-Learning-com-Python-de-A-a-Z/blob/master/Tarefa_14_Recomendacao_Filmes_Restricted_Boltzmann_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Maquina RBM Codigo:
[link text](https://github.com/echen/restricted-boltzmann-machines)

In [0]:
from rbm import RBM
import numpy as np

In [0]:
filmes = ["A Disney", "A Disney Retorna", "Ta na Disney ###", "Perdidos em Marte", "Interstellar", "Apollo 13"]

In [0]:
rbm = RBM(num_visible = 6, num_hidden = 3)
base = np.array([[0, 1, 1, 1, 0, 1],
                 [1, 1, 0, 1, 1, 1],
                 [0, 1, 0, 1, 0, 1],
                 [0, 1, 1, 1, 0, 1],
                 [1, 1, 0, 1, 0, 1],
                 [1, 1, 0, 1, 1, 1]])

In [4]:
rbm.train(base, max_epochs = 5000)#autor indica 5000 para maximo de epochs, mais do que isso é overfeeding

Streaming output truncated to the last 5000 lines.
Epoch 1: error is 8.514320216004135
Epoch 2: error is 8.015431395428656
Epoch 3: error is 7.787081387980869
Epoch 4: error is 7.254814066797202
Epoch 5: error is 6.943156071488612
Epoch 6: error is 6.239808786310616
Epoch 7: error is 6.266183605550472
Epoch 8: error is 6.175602403267963
Epoch 9: error is 5.797375161934427
Epoch 10: error is 5.663721592534255
Epoch 11: error is 5.475952750899796
Epoch 12: error is 5.84453156380264
Epoch 13: error is 4.874347979827182
Epoch 14: error is 4.932183499419484
Epoch 15: error is 4.900385560398424
Epoch 16: error is 4.884988631551056
Epoch 17: error is 4.640281215425999
Epoch 18: error is 4.936459279621333
Epoch 19: error is 4.626088278911485
Epoch 20: error is 4.718928390173328
Epoch 21: error is 4.41862044985803
Epoch 22: error is 4.639535076951504
Epoch 23: error is 4.3914057965861755
Epoch 24: error is 4.7666754396129996
Epoch 25: error is 4.651257516294046
Epoch 26: error is 4.603917021633

In [10]:
rbm.weights #segunda e terceira coluna = unidade bias, cada linha a partir da segunda representa 1 filme

array([[ 0.84151631, -1.13601876, -1.07036449,  0.08282588],
       [ 1.74160587,  1.91971934,  2.0257151 , -7.49254912],
       [ 3.56944038,  1.1868656 ,  1.22348478,  1.82321055],
       [-0.32629754, -5.43380736, -5.60693924,  5.9159564 ],
       [ 3.57441691,  1.21648778,  1.17007438,  1.84769546],
       [ 0.11323653,  0.37267342,  0.40195517, -5.92547686],
       [ 3.59693917,  1.17638301,  1.20427172,  1.80492175]])

In [0]:
usuario_1 = np.array([[0, 1, 0, 1, 0, 0]])

In [12]:
resultado_1 = rbm.run_visible(usuario_1)#ativou o segundo neuronio, o primeiro neuronio não foi ativado
resultado_1

array([[1., 1., 1.]])

In [13]:
recomendacao_1 = rbm.run_hidden(resultado_1)
recomendacao_1

array([[0., 1., 0., 1., 0., 1.]])

In [14]:
for cont, value in enumerate(usuario_1[0]):
  if value == 0 and recomendacao_1[0, cont] == 1:
    print(filmes[cont])

Apollo 13
